### ISSUE TITLE
Discussion about ipython-sql

### ISSUE THREAD

**Issue by kindly** [OpenDataServices/noteql#2]
Hello @catherinedevlin 

I have been working on this library and now am feeling guilty that it is turning out to be kind of a fork (in concept only) of ipython-sql.  If you have time please read over the README and see what you think.

Ideally there would not be two libraries doing similar things but I think merging them may be too difficult.
I just wanted to be a good open source citizen to inform you that I am working on this to see if there was any chance of collaboration and also to see if I could get any learnings off you from writing ipython-sql.

I have gone for a slightly different approach in having a `session` object for defining the connections and written parser (using pyparsing) for the magic lines/cell parsing which has made the magic lines more like SQL itself.  This has worked out well and it is now fairly easy to add any new features/syntax. 

If you read this, thank you for your time!!

**Comment by jpmckinney** [comment]
FYI, ipython-sql now suggests the fork jupysql https://github.com/ploomber/jupysql
